"""Synthesis (v2.1): deterministic verdict math + CoT LLM reasoning + report assembly.

LLM emits 4 fields: reasoning, key_drivers, dissenting_view, watch_items.
Verdict / conviction / confidence remain deterministic upstream.
"""

from __future__ import annotations

from datetime import datetime, timezone
from statistics import mean

from agents import safe_parse_json
from state import Conviction, Verdict


SCORE_MAP = {"BULLISH": 1, "NEUTRAL": 0, "BEARISH": -1}
AGENT_ORDER = ["price", "sentiment", "fundamentals", "macro", "risk"]
SECTION_TITLES = {
    "price": "Technical Analysis",
    "sentiment": "News & Sentiment",
    "fundamentals": "Fundamentals",
    "macro": "Macro Backdrop",
    "risk": "Risk Profile",
}

LABEL_TABLE: dict[tuple[str, str], str] = {
    ("BUY", "STRONG"): "Strong Buy",
    ("BUY", "STANDARD"): "Buy",
    ("BUY", "CAUTIOUS"): "Cautious Buy",
    ("HOLD", "STRONG"): "Hold (High Conviction)",
    ("HOLD", "STANDARD"): "Hold",
    ("HOLD", "CAUTIOUS"): "Hold (Mixed Signals)",
    ("SELL", "STRONG"): "Strong Sell",
    ("SELL", "STANDARD"): "Sell",
    ("SELL", "CAUTIOUS"): "Cautious Sell",
}


PERSONA = (
    "You are the Chief Investment Officer and Director of Research at a "
    "multi-strategy fund. You chair the daily investment committee — your "
    "job is to integrate five specialist signals into a single coherent "
    "thesis, name the strongest argument for the call AND the strongest "
    "argument against, and identify the leading indicators that would force "
    "a re-evaluation. You never overstate confidence and you always make "
    "dissent visible."
)

COT = """
The verdict, conviction, and confidence are already decided upstream from
specialist signals — you write the NARRATIVE.

Reason step-by-step:
1. Consensus — which agents agree with the verdict? At what avg confidence?
2. Dissent — which agents disagree? Why? (Cite their summary)
3. Strongest single argument FOR — name the specialist + metric
4. Strongest single argument AGAINST — name the specialist + metric
5. Integrated thesis — 3-5 sentences referencing ≥3 specialists by name
6. Key drivers — 2-4 phrases, each "Specialist: <metric/observation>"
7. Dissenting view — one sentence: what condition flips the call
8. Watch items — 2-3 leading indicators (rate prints, earnings dates,
   VIX thresholds, segment growth) that would force a re-rating

Output JSON only.
""".strip()

OUTPUT_SCHEMA = """
Respond with a single JSON object (no markdown fences) with EXACTLY these keys:
{
  "reasoning": "3-5 sentences (80-150 words) referencing ≥3 specialists by name",
  "key_drivers": ["Specialist: metric/observation", ...],   // 2-4 entries, each ≤15 words
  "dissenting_view": "one sentence ≤25 words: what condition flips the call",
  "watch_items": ["leading indicator", ...]                  // 2-3 entries, each ≤20 words
}
""".strip()


def label_for(verdict: Verdict, conviction: Conviction) -> str:
    return LABEL_TABLE[(verdict, conviction)]


def compute_verdict_and_conviction(signals: list[dict]) -> tuple[Verdict, Conviction, float]:
    contributions = []
    for s in signals:
        weight = float(s.get("confidence", 0.0)) * (0.0 if s.get("degraded") else 1.0)
        contributions.append(SCORE_MAP.get(s.get("signal", "NEUTRAL"), 0) * weight)
    net = sum(contributions) / 5.0

    if net > 0.20:
        verdict: Verdict = "BUY"
    elif net < -0.20:
        verdict = "SELL"
    else:
        verdict = "HOLD"

    target_score = SCORE_MAP[{"BUY": "BULLISH", "SELL": "BEARISH", "HOLD": "NEUTRAL"}[verdict]]
    agreeing = [
        s for s in signals
        if not s.get("degraded") and SCORE_MAP.get(s.get("signal", "NEUTRAL"), 0) == target_score
    ]
    agree_count = len(agreeing)
    avg_conf = mean(float(s["confidence"]) for s in agreeing) if agreeing else 0.0

    if agree_count >= 4 and avg_conf >= 0.75:
        conviction: Conviction = "STRONG"
    elif agree_count >= 3 and avg_conf >= 0.55:
        conviction = "STANDARD"
    else:
        conviction = "CAUTIOUS"

    non_degraded = [s for s in signals if not s.get("degraded")]
    if not non_degraded:
        return "HOLD", "CAUTIOUS", 0.0
    base = mean(float(s["confidence"]) for s in non_degraded)
    final_conf = round(base * (len(non_degraded) / 5.0), 3)
    return verdict, conviction, final_conf


def _section_for(signals: list[dict], agent: str) -> str:
    for s in signals:
        if s.get("agent") == agent:
            md = (s.get("section_markdown") or "").strip()
            if md and md.startswith("## "):
                lines = md.split("\n", 1)
                content = lines[1] if len(lines) > 1 else ""
                return f"## {SECTION_TITLES[agent]}\n{content.strip()}"
            return f"## {SECTION_TITLES[agent]}\n{md or '_Section unavailable._'}"
    return f"## {SECTION_TITLES[agent]}\n_Agent did not run._"


def _disclaimer_block() -> str:
    return (
        "## Disclaimer\n"
        "This report is generated by an AI system and is not financial advice. "
        "Data sources: yfinance (price/risk), Tavily (news), SEC EDGAR (fundamentals), "
        "FRED + Fear & Greed Index (macro). Numbers are point-in-time at run; "
        "agent confidences and the final verdict reflect machine inference and may be wrong. "
        "Do your own research before any investment decision."
    )


def synthesis_agent(state: dict, clients) -> dict:
    ticker = state["ticker"]
    company = state.get("company_name") or ticker
    signals = state.get("agent_signals", []) or []
    review = state.get("supervisor_review") or {"notes": "", "critiques": {}}

    verdict, conviction, confidence = compute_verdict_and_conviction(signals)
    label = label_for(verdict, conviction)

    rollup = "\n".join(
        f"- {s['agent'].upper()}: {s.get('signal', 'NEUTRAL')} "
        f"(conf {float(s.get('confidence', 0.0)):.2f}{', degraded' if s.get('degraded') else ''}) — {s.get('summary', '')}"
        for s in signals
    )

    user_prompt = (
        f"Ticker: {ticker} ({company})\n"
        f"Deterministic verdict: **{label}** "
        f"(verdict={verdict}, conviction={conviction}, confidence={confidence:.2f})\n\n"
        f"Specialist rollup:\n{rollup}\n\n"
        f"Supervisor notes: {review.get('notes', '')}\n\n"
        "Run your 8-step chain of thought, then output the final JSON."
    )

    system_prompt = "\n\n".join([PERSONA, COT, OUTPUT_SCHEMA])

    reasoning = ""
    key_drivers: list = []
    dissenting_view = ""
    watch_items: list = []
    try:
        resp = clients.reasoning.invoke([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ])
        out = safe_parse_json(resp.content)
        reasoning = out.get("reasoning") or ""
        key_drivers = list(out.get("key_drivers") or [])
        dissenting_view = out.get("dissenting_view") or ""
        watch_items = list(out.get("watch_items") or [])
    except Exception as exc:
        reasoning = (
            f"Synthesis LLM call failed ({str(exc)[:100]}). "
            f"Verdict {label} is derived deterministically from the specialist signals above."
        )

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    drivers_block = (
        "\n\n**Key drivers:**\n" + "\n".join(f"- {d}" for d in key_drivers)
        if key_drivers else ""
    )

    exec_summary = (
        f"# {ticker} — {company}\n\n"
        f"_Generated {timestamp}_\n\n"
        f"## Executive Summary\n"
        f"**Verdict: {label}** · Confidence: {confidence * 100:.0f}%\n\n"
        f"- Verdict: {verdict}\n"
        f"- Conviction: {conviction}\n"
        f"- {review.get('notes', '')}"
        f"{drivers_block}\n"
    )

    synthesis_block = (
        f"## Synthesis & Final Verdict\n"
        f"**{label}** — Confidence {confidence * 100:.0f}%.\n\n"
        f"{reasoning}"
    )
    if dissenting_view:
        synthesis_block += f"\n\n_Dissenting view: {dissenting_view}_"
    if watch_items:
        synthesis_block += "\n\n### What to Watch\n" + "\n".join(
            f"- {w}" for w in watch_items
        )

    sections = [
        exec_summary,
        _section_for(signals, "price"),
        _section_for(signals, "sentiment"),
        _section_for(signals, "fundamentals"),
        _section_for(signals, "macro"),
        _section_for(signals, "risk"),
        synthesis_block,
        _disclaimer_block(),
    ]
    final_report = "\n\n".join(sections)

    return {
        "final_verdict": verdict,
        "final_conviction": conviction,
        "final_confidence": confidence,
        "final_reasoning": reasoning,
        "final_report": final_report,
        "key_drivers": key_drivers,
        "dissenting_view": dissenting_view,
        "watch_items": watch_items,
    }
